### PR TITLE
Release v1.1

### PR DESCRIPTION
**Pull request by Dirbaio**

### CODE REVIEW

**Review by eldruin — COMMENTED** [review]
Could we also add links to the changes in the version numbers like [here](https://github.com/rust-embedded/embedded-hal/blob/master/CHANGELOG.md)

**Comment by Dirbaio** [comment]
@eldruin DONE! :D

**Review by eldruin — APPROVED** [review]
Thank you!
bors r+

**Comment by Dirbaio** [comment]
Released v1.1.0 :rocket:

**Pull request merged**
